model:
    pos_enc: "learnable" # None, "sinusoidal", "learnable"
    rel_idx: False
    rel_time: False
    rel_pitch: False
    linear: False
    hadamard: False
    attn_only: True
    dim: 256
    depth: 8
    heads: 16
    max_note_len: 1024
    dropout: 0.2
data:
    batch_size: 32
train:
    accumulation_steps: 1
music_rep: "NoteTuple"