model:
    pos_enc: "learnable" # None, "sinusoidal", "learnable"
    rel_idx: True
    rel_time: True
    rel_pitch: True
    linear: True
    hadamard: True
    attn_only: True
    alpha: 0.1
    dim: 256
    depth: 8
    max_note_len: 1024
    dropout: 0.2
data:
    batch_size: 32
train:
    accumulation_steps: 1
music_rep: "NoteTuple"