model:
    pos_enc: "learnable" # None, "sinusoidal", "learnable"
    rel_idx: True
    rel_time: True
    rel_pitch: True
    linear: False
    hadamard: False
data:
    batch_size: 8
train:
    accumulation_steps: 1
music_rep: "NoteTuple"